services:
  waiter:
    image: busybox:1.35.0-uclibc
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16.8-alpine3.20
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST:
      POSTGRES_PORT:
      POSTGRES_HOST_AUTH_METHOD:
    command: ["postgres", "-c", "max_connections=400"]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30
